title: Alex Outkou # your name (or website title) here
logo: "/images/self.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/alex-outkou/">LinkedIn</a> 
  <br>
  <a href="MyResume1.pdf" class="btn btn--info">Resume</a>   
  <br>
  <a href="https://www.GitHub.com/ado323/">GitHub</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">Twitter</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">Youtube</a> 
  
theme: jekyll-theme-minimal
